### PR TITLE
Exposes darwin notification sending in public header

### PR DESCRIPTION
**Pull request by felixLam**
We wanted to send a notification without data. This PR simply exposes the darwin method in the public header. Also, because the instance method made no references to the state I moved it to a class method. To minimize the changes, I kept the internal instance method. Let me know if this is helpful.

### CODE REVIEW

**Comment by cnstoll** [comment]
Hey Felix,

This seems like an interesting change. I'm curious though, why not just pass a message with an empty string as the parameter?

I'm not opposed to adding this, I'm just trying to think it through a bit more before adding more methods to the public interface. Any other thoughts on how this would be used?

On a side note, I started using Trails about 5 years ago. Good to hear from you!!

Thanks,

- Conrad

**Comment by felixLam** [comment]
Hi Conrad,

glad to hear you like our app. Have you seen the new version https://trails.io?

Sending a message without data is not possible due to the early return in https://github.com/mutualmobile/MMWormhole/blob/master/Source/MMWormhole.m#L125.

I wanted to avoid any disk interaction as we need to send this message up to every second or so. Writing an empty string to disk felt unnecessary.  

If you are Ok with this method, I will add the missing documentation. 

In addition the we should probably add an early return if the `messageObject` is `nil` in https://github.com/mutualmobile/MMWormhole/blob/master/Source/MMWormhole.m#L117. I am not sure how well `NSKeyedArchiver` handles `nil`. In any case there is some work to be avoided.

Thanks for this cool tool. It helped us a lot.

Kind regards,

Felix

**Comment by cnstoll** [comment]
I hadn't seen the new version yet, but it looks great! I'll definitely try it out.

Here's what I'm thinking. I hesitate to add another method to the public interface, mostly just because I like how simple the interface is already. I'm not completely opposed to it, but what about this instead.

Why don't we just add the following above this line you linked, https://github.com/mutualmobile/MMWormhole/blob/master/Source/MMWormhole.m#L125.

```
[self sendNotificationForMessageWithIdentifier:identifier];
```

That way it supports sending notifications just by passing nil as the message.

The disadvantage is that it would still require you to instantiate MMWormhole since that method is an instance method. Does that seem reasonable given the use-cases you've envisioned? I know an instance of the class isn't really necessary to perform this action, but so far everything else on the class is an instance method, and it feels weird to add a class method to it. Any thoughts there?

Thanks,

- Conrad

**Comment by felixLam** [comment]
Hi Conrad,

that would definitely work for us. I was hesitating to implement that option as others might rely on the fact that `nil` does not trigger a notification at all. 

Do you prefer to make the changes yourself, or do you want me to open a second PR?

Thanks,

Felix

**Comment by cnstoll** [comment]
That's a good point. I think it'll be ok though.

The only danger to all of this that I can see is that if there is already a message for that identifier, then any listeners for that notification will fire and return potentially old data. But, that would be a problem with doing this as a class method anyway, so I guess it's ok. It's hard for me to imagine a case where that would trip someone up.

Would you like to make the change in a second PR? I'd kind of like you to get commit credit for it, since this was mostly your idea :)

Thanks,

- Conrad

**Comment by iblacksun** [comment]
I have same issue, how about this PR now?

**Comment by cnstoll** [comment]
Still waiting on the other changes to modify the writeMessageObject method. I just haven't heard back from Felix if he'd like to make that change or wants me to.

**Comment by felixLam** [comment]
Sorry for the delay. We were somewhat busy on our Watch app ;)

**Comment by cnstoll** [comment]
Hehe...no worries. I'm in the same boat :)

**Comment by cnstoll** [comment]
Merged in the other PR. Thanks everyone.

**Pull request closed without merging**
