### PR TITLE
Run xcode 10 migration wizard

### PR DESCRIPTION
**Pull request by edelabar**
Ran the Xcode 10 migration wizard, no code changes.

We use this project as a submodule off a tag, it would be greatly appreciated if you could merge this a create a new tag from it so we can kill the Xcode warnings. Thanks!

### CODE REVIEW

**Review by cnstoll — APPROVED** [review]
Nice! Looks good to me. Thanks for running the updater.

**Comment by ghost** [comment]
2.0.10 is tagged and pushed to GH 👍

**Review by dataman713 — COMMENTED** [review]
``

**Comment by dataman713** [comment]
``

**Pull request merged**
